<?php
// file: config_templates-dist.php.
// copyright : (C) 2008-2012 Edwin2Win sprlu - all right reserved.
// author: www.jms2win.com - info@jms2win.com
/* license: 
This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
A full text version of the GNU GPL version 2 can be found in the LICENSE.php file.
*/
?><?php
if( !defined( '_JEXEC' )) die( 'Direct Access to '.basename(__FILE__).' is not allowed.' );
$templates = array();
$templates['freshSlaveDomain'] = array(
'fromSiteID' => '',
'groupName' => '',
'sku' => '',
'title' => '',
'description' => 'Assume that the Site ID will be mydomain.com
and deployed in directory
/home/ACCOUNT/domains/mydomain.com/public_html',
'validity' => '0',
'validity_unit' => 'days',
'maxsite' => '0',
'expireurl' => '',
'toDomains' => array( 'http://www.{site_id}', 'http://{site_id}'),
'redirect1st' => '',
'ignoreMasterIndex' => '',
'continents' => array( ),
'countries' => array( ),
'regions' => '',
'states' => '',
'cities' => '',
'zipcodes' => '',
'fromLongitude' => '',
'fromLatitude' => '',
'toLongitude' => '',
'toLatitude' => '',
'metro' => '',
'area' => '',
'geoip_ignoreundefined' => '0',
'geoip_ignorepattern' => '',
'geoip_ignoretimeout' => '0',
'sortOrdering' => '',
'browser_types' => array( ),
'browser_langs' => '',
'browser_ignorepattern' => '',
'browser_ignoretimeout' => '0',
'toSiteID' => '',
'shareDB' => '',
'adminUserID' => '',
'adminUserLogin' => '',
'adminUserName' => '',
'adminUserEmail' => '',
'adminUserPsw' => '',
'toPrefix' => '',
'toSiteName' => '',
'setDefaultJLang' => '',
'setDefaultTemplate' => '',
'setDefaultMenu' => '',
'deploy_dir' => '{home}/domains/{site_id-2}.{site_id-1}{public}',
'media_dir' => '',
'images_dir' => '',
'toFTP_enable' => '[unselected]',
'symboliclinks' => array( '_installation' => array( 'action' => 'ignore'),
'administrator' => array( 'action' => 'SL'),
'cache' => array( 'action' => 'mkdir', 'readOnly' => '1'),
'cli' => array( 'action' => 'SL'),
'components' => array( 'action' => 'SL'),
'images' => array( 'action' => 'special'),
'includes' => array( 'action' => 'SL'),
'installation' => array( 'action' => 'dirlinks'),
'language' => array( 'action' => 'SL'),
'libraries' => array( 'action' => 'SL'),
'logs' => array( 'action' => 'mkdir', 'readOnly' => '1'),
'media' => array( 'action' => 'SL'),
'modules' => array( 'action' => 'SL'),
'multisites' => array( 'action' => 'SL'),
'plugins' => array( 'action' => 'SL'),
'templates' => array( 'action' => 'special'),
'tmp' => array( 'action' => 'mkdir', 'readOnly' => '1'),
'LICENSE.txt' => array( 'action' => 'SL'),
'README.txt' => array( 'action' => 'SL'),
'build.xml' => array( 'action' => 'SL'),
'defines.php' => array( 'action' => 'SL'),
'htaccess.txt' => array( 'action' => 'SL'),
'joomla.xml' => array( 'action' => 'SL'),
'robots.txt' => array( 'action' => 'SL'),
'web.config.txt' => array( 'action' => 'SL'),
'index.php' => array( 'action' => 'redirect', 'readOnly' => '1'),
'index2.php' => array( 'action' => 'redirect', 'readOnly' => '1')));
$templates['freshSlaveMultisites'] = array(
'fromSiteID' => '',
'groupName' => '',
'sku' => '',
'title' => '',
'description' => '',
'validity' => '0',
'validity_unit' => 'days',
'maxsite' => '0',
'expireurl' => '',
'toDomains' => array( 'http://{site_url}/multisites/{site_id}'),
'redirect1st' => '',
'ignoreMasterIndex' => '',
'continents' => array( ),
'countries' => array( ),
'regions' => '',
'states' => '',
'cities' => '',
'zipcodes' => '',
'fromLongitude' => '',
'fromLatitude' => '',
'toLongitude' => '',
'toLatitude' => '',
'metro' => '',
'area' => '',
'geoip_ignoreundefined' => '0',
'geoip_ignorepattern' => '',
'geoip_ignoretimeout' => '0',
'sortOrdering' => '',
'browser_types' => array( ),
'browser_langs' => '',
'browser_ignorepattern' => '',
'browser_ignoretimeout' => '0',
'toSiteID' => '',
'shareDB' => '',
'adminUserID' => '',
'adminUserLogin' => '',
'adminUserName' => '',
'adminUserEmail' => '',
'adminUserPsw' => '',
'toPrefix' => '',
'toSiteName' => '',
'setDefaultJLang' => '',
'setDefaultTemplate' => '',
'setDefaultMenu' => '',
'deploy_dir' => '{site_dir}',
'media_dir' => '',
'images_dir' => '',
'toFTP_enable' => '[unselected]',
'symboliclinks' => array( '_installation' => array( 'action' => 'ignore'),
'administrator' => array( 'action' => 'SL'),
'cache' => array( 'action' => 'mkdir', 'readOnly' => '1'),
'cli' => array( 'action' => 'SL'),
'components' => array( 'action' => 'SL'),
'images' => array( 'action' => 'special'),
'includes' => array( 'action' => 'SL'),
'installation' => array( 'action' => 'dirlinks'),
'language' => array( 'action' => 'SL'),
'libraries' => array( 'action' => 'SL'),
'logs' => array( 'action' => 'mkdir', 'readOnly' => '1'),
'media' => array( 'action' => 'SL'),
'modules' => array( 'action' => 'SL'),
'multisites' => array( 'action' => 'SL'),
'plugins' => array( 'action' => 'SL'),
'templates' => array( 'action' => 'special'),
'tmp' => array( 'action' => 'mkdir', 'readOnly' => '1'),
'LICENSE.txt' => array( 'action' => 'SL'),
'README.txt' => array( 'action' => 'SL'),
'build.xml' => array( 'action' => 'SL'),
'defines.php' => array( 'action' => 'SL'),
'htaccess.txt' => array( 'action' => 'SL'),
'joomla.xml' => array( 'action' => 'SL'),
'robots.txt' => array( 'action' => 'SL'),
'web.config.txt' => array( 'action' => 'SL'),
'index.php' => array( 'action' => 'redirect', 'readOnly' => '1'),
'index2.php' => array( 'action' => 'redirect', 'readOnly' => '1')));
$templates['freshSlaveSubdir'] = array(
'fromSiteID' => '',
'groupName' => '',
'sku' => '',
'title' => '',
'description' => '',
'validity' => '0',
'validity_unit' => 'days',
'maxsite' => '0',
'expireurl' => '',
'toDomains' => array( 'http://{site_url}/{site_id}'),
'redirect1st' => '',
'ignoreMasterIndex' => '',
'continents' => array( ),
'countries' => array( ),
'regions' => '',
'states' => '',
'cities' => '',
'zipcodes' => '',
'fromLongitude' => '',
'fromLatitude' => '',
'toLongitude' => '',
'toLatitude' => '',
'metro' => '',
'area' => '',
'geoip_ignoreundefined' => '0',
'geoip_ignorepattern' => '',
'geoip_ignoretimeout' => '0',
'sortOrdering' => '',
'browser_types' => array( ),
'browser_langs' => '',
'browser_ignorepattern' => '',
'browser_ignoretimeout' => '0',
'toSiteID' => '',
'shareDB' => '',
'adminUserID' => '',
'adminUserLogin' => '',
'adminUserName' => '',
'adminUserEmail' => '',
'adminUserPsw' => '',
'toPrefix' => '',
'toSiteName' => '',
'setDefaultJLang' => '',
'setDefaultTemplate' => '',
'setDefaultMenu' => '',
'deploy_dir' => '{root}/{site_id}',
'deploy_create' => 'on',
'media_dir' => '',
'images_dir' => '',
'toFTP_enable' => '[unselected]',
'symboliclinks' => array( '_installation' => array( 'action' => 'ignore'),
'administrator' => array( 'action' => 'SL'),
'cache' => array( 'action' => 'mkdir', 'readOnly' => '1'),
'cli' => array( 'action' => 'SL'),
'components' => array( 'action' => 'SL'),
'images' => array( 'action' => 'special'),
'includes' => array( 'action' => 'SL'),
'installation' => array( 'action' => 'dirlinks'),
'language' => array( 'action' => 'SL'),
'libraries' => array( 'action' => 'SL'),
'logs' => array( 'action' => 'mkdir', 'readOnly' => '1'),
'media' => array( 'action' => 'SL'),
'modules' => array( 'action' => 'SL'),
'multisites' => array( 'action' => 'SL'),
'plugins' => array( 'action' => 'SL'),
'templates' => array( 'action' => 'special'),
'tmp' => array( 'action' => 'mkdir', 'readOnly' => '1'),
'LICENSE.txt' => array( 'action' => 'SL'),
'README.txt' => array( 'action' => 'SL'),
'build.xml' => array( 'action' => 'SL'),
'defines.php' => array( 'action' => 'SL'),
'htaccess.txt' => array( 'action' => 'SL'),
'joomla.xml' => array( 'action' => 'SL'),
'robots.txt' => array( 'action' => 'SL'),
'web.config.txt' => array( 'action' => 'SL'),
'index.php' => array( 'action' => 'redirect', 'readOnly' => '1'),
'index2.php' => array( 'action' => 'redirect', 'readOnly' => '1')));
$templates['freshSlaveSubdomain'] = array(
'fromSiteID' => '',
'groupName' => '',
'sku' => '',
'title' => '',
'description' => 'Assume that the Site ID will be subdomain.mydomain.com
and deployed in directory
/home/ACCOUNT/domains/mydomain.com/subdomains/subdomain/public_html',
'validity' => '0',
'validity_unit' => 'days',
'maxsite' => '0',
'expireurl' => '',
'toDomains' => array( 'http://{site_id}', 'http://www.{site_id}'),
'redirect1st' => '',
'ignoreMasterIndex' => '',
'continents' => array( ),
'countries' => array( ),
'regions' => '',
'states' => '',
'cities' => '',
'zipcodes' => '',
'fromLongitude' => '',
'fromLatitude' => '',
'toLongitude' => '',
'toLatitude' => '',
'metro' => '',
'area' => '',
'geoip_ignoreundefined' => '0',
'geoip_ignorepattern' => '',
'geoip_ignoretimeout' => '0',
'sortOrdering' => '',
'browser_types' => array( ),
'browser_langs' => '',
'browser_ignorepattern' => '',
'browser_ignoretimeout' => '0',
'toSiteID' => '',
'shareDB' => '',
'adminUserID' => '',
'adminUserLogin' => '',
'adminUserName' => '',
'adminUserEmail' => '',
'adminUserPsw' => '',
'toPrefix' => '',
'toSiteName' => '',
'setDefaultJLang' => '',
'setDefaultTemplate' => '',
'setDefaultMenu' => '',
'deploy_dir' => '{home}/domains/{site_id-2}.{site_id-1}/subdomains/{site_id-3}{public}',
'media_dir' => '',
'images_dir' => '',
'toFTP_enable' => '[unselected]',
'symboliclinks' => array( '_installation' => array( 'action' => 'ignore'),
'administrator' => array( 'action' => 'SL'),
'cache' => array( 'action' => 'mkdir', 'readOnly' => '1'),
'cli' => array( 'action' => 'SL'),
'components' => array( 'action' => 'SL'),
'images' => array( 'action' => 'special'),
'includes' => array( 'action' => 'SL'),
'installation' => array( 'action' => 'dirlinks'),
'language' => array( 'action' => 'SL'),
'libraries' => array( 'action' => 'SL'),
'logs' => array( 'action' => 'mkdir', 'readOnly' => '1'),
'media' => array( 'action' => 'SL'),
'modules' => array( 'action' => 'SL'),
'multisites' => array( 'action' => 'SL'),
'plugins' => array( 'action' => 'SL'),
'templates' => array( 'action' => 'special'),
'tmp' => array( 'action' => 'mkdir', 'readOnly' => '1'),
'LICENSE.txt' => array( 'action' => 'SL'),
'README.txt' => array( 'action' => 'SL'),
'build.xml' => array( 'action' => 'SL'),
'defines.php' => array( 'action' => 'SL'),
'htaccess.txt' => array( 'action' => 'SL'),
'joomla.xml' => array( 'action' => 'SL'),
'robots.txt' => array( 'action' => 'SL'),
'web.config.txt' => array( 'action' => 'SL'),
'index.php' => array( 'action' => 'redirect', 'readOnly' => '1'),
'index2.php' => array( 'action' => 'redirect', 'readOnly' => '1')));
$templates['replicMasterDomain'] = array(
'fromSiteID' => ':master_db:',
'groupName' => '',
'sku' => '',
'title' => '',
'description' => 'Assume that the Site ID will be mydomain.com
and deployed in directory
/home/ACCOUNT/domains/mydomain.com/public_html',
'validity' => '0',
'validity_unit' => 'days',
'maxsite' => '0',
'expireurl' => '',
'toDomains' => array( 'http://www.{site_id}', 'http://{site_id}'),
'redirect1st' => '',
'ignoreMasterIndex' => '',
'continents' => array( ),
'countries' => array( ),
'regions' => '',
'states' => '',
'cities' => '',
'zipcodes' => '',
'fromLongitude' => '',
'fromLatitude' => '',
'toLongitude' => '',
'toLatitude' => '',
'metro' => '',
'area' => '',
'geoip_ignoreundefined' => '0',
'geoip_ignorepattern' => '',
'geoip_ignoretimeout' => '0',
'sortOrdering' => '',
'browser_types' => array( ),
'browser_langs' => '',
'browser_ignorepattern' => '',
'browser_ignoretimeout' => '0',
'toSiteID' => '',
'shareDB' => '',
'adminUserID' => '0',
'adminUserLogin' => '',
'adminUserName' => '',
'adminUserEmail' => '',
'adminUserPsw' => '',
'toPrefix' => '{site_id}_',
'toSiteName' => '',
'setDefaultJLang' => '',
'setDefaultTemplate' => '',
'setDefaultMenu' => '',
'deploy_dir' => '{home}/domains/{site_id-2}.{site_id-1}{public}',
'toFTP_enable' => '[unselected]',
'symboliclinks' => array( '.settings' => array( 'action' => 'ignore'),
'_installation' => array( 'action' => 'ignore'),
'administrator' => array( 'action' => 'SL'),
'cache' => array( 'action' => 'mkdir', 'readOnly' => '1'),
'components' => array( 'action' => 'SL'),
'images' => array( 'action' => 'special'),
'includes' => array( 'action' => 'SL'),
'installation' => array( 'action' => 'ignore'),
'language' => array( 'action' => 'SL'),
'libraries' => array( 'action' => 'SL'),
'logs' => array( 'action' => 'mkdir', 'readOnly' => '1'),
'media' => array( 'action' => 'SL'),
'modules' => array( 'action' => 'SL'),
'multisites' => array( 'action' => 'SL'),
'plugins' => array( 'action' => 'SL'),
'templates' => array( 'action' => 'special'),
'tmp' => array( 'action' => 'mkdir', 'readOnly' => '1'),
'xmlrpc' => array( 'action' => 'SL'),
'.buildpath' => array( 'action' => 'ignore'),
'.project' => array( 'action' => 'ignore'),
'htaccess.txt' => array( 'action' => 'SL'),
'robots.txt' => array( 'action' => 'SL'),
'index.php' => array( 'action' => 'redirect', 'readOnly' => '1'),
'index2.php' => array( 'action' => 'redirect', 'readOnly' => '1')),
'dbsharing' => array( ));
$templates['replicMasterMultisites'] = array(
'fromSiteID' => ':master_db:',
'groupName' => '',
'sku' => '',
'title' => '',
'description' => '',
'validity' => '0',
'validity_unit' => 'days',
'maxsite' => '0',
'expireurl' => '',
'toDomains' => array( 'http://{site_url}/multisites/{site_id}'),
'redirect1st' => '',
'ignoreMasterIndex' => '',
'continents' => array( ),
'countries' => array( ),
'regions' => '',
'states' => '',
'cities' => '',
'zipcodes' => '',
'fromLongitude' => '',
'fromLatitude' => '',
'toLongitude' => '',
'toLatitude' => '',
'metro' => '',
'area' => '',
'geoip_ignoreundefined' => '0',
'geoip_ignorepattern' => '',
'geoip_ignoretimeout' => '0',
'sortOrdering' => '',
'browser_types' => array( ),
'browser_langs' => '',
'browser_ignorepattern' => '',
'browser_ignoretimeout' => '0',
'toSiteID' => '',
'shareDB' => '',
'adminUserID' => '0',
'adminUserLogin' => '',
'adminUserName' => '',
'adminUserEmail' => '',
'adminUserPsw' => '',
'toPrefix' => '{site_id}_',
'toSiteName' => '',
'setDefaultJLang' => '',
'setDefaultTemplate' => '',
'setDefaultMenu' => '',
'deploy_dir' => '{site_dir}',
'toFTP_enable' => '[unselected]',
'symboliclinks' => array( '.settings' => array( 'action' => 'ignore'),
'_installation' => array( 'action' => 'ignore'),
'administrator' => array( 'action' => 'SL'),
'cache' => array( 'action' => 'mkdir', 'readOnly' => '1'),
'components' => array( 'action' => 'SL'),
'images' => array( 'action' => 'special'),
'includes' => array( 'action' => 'SL'),
'installation' => array( 'action' => 'ignore'),
'language' => array( 'action' => 'SL'),
'libraries' => array( 'action' => 'SL'),
'logs' => array( 'action' => 'mkdir', 'readOnly' => '1'),
'media' => array( 'action' => 'SL'),
'modules' => array( 'action' => 'SL'),
'multisites' => array( 'action' => 'SL'),
'plugins' => array( 'action' => 'SL'),
'templates' => array( 'action' => 'special'),
'tmp' => array( 'action' => 'mkdir', 'readOnly' => '1'),
'xmlrpc' => array( 'action' => 'SL'),
'.buildpath' => array( 'action' => 'ignore'),
'.project' => array( 'action' => 'ignore'),
'htaccess.txt' => array( 'action' => 'SL'),
'robots.txt' => array( 'action' => 'SL'),
'index.php' => array( 'action' => 'redirect', 'readOnly' => '1'),
'index2.php' => array( 'action' => 'redirect', 'readOnly' => '1')),
'dbsharing' => array( ));
$templates['replicMasterSubdir'] = array(
'fromSiteID' => ':master_db:',
'groupName' => '',
'sku' => '',
'title' => '',
'description' => '',
'validity' => '0',
'validity_unit' => 'days',
'maxsite' => '0',
'expireurl' => '',
'toDomains' => array( 'http://{site_url}/{site_id}'),
'redirect1st' => '',
'ignoreMasterIndex' => '',
'continents' => array( ),
'countries' => array( ),
'regions' => '',
'states' => '',
'cities' => '',
'zipcodes' => '',
'fromLongitude' => '',
'fromLatitude' => '',
'toLongitude' => '',
'toLatitude' => '',
'metro' => '',
'area' => '',
'geoip_ignoreundefined' => '0',
'geoip_ignorepattern' => '',
'geoip_ignoretimeout' => '0',
'sortOrdering' => '',
'browser_types' => array( ),
'browser_langs' => '',
'browser_ignorepattern' => '',
'browser_ignoretimeout' => '0',
'toSiteID' => '',
'shareDB' => '',
'adminUserID' => '0',
'adminUserLogin' => '',
'adminUserName' => '',
'adminUserEmail' => '',
'adminUserPsw' => '',
'toPrefix' => '{site_id}_',
'toSiteName' => '',
'setDefaultJLang' => '',
'setDefaultTemplate' => '',
'setDefaultMenu' => '',
'deploy_dir' => '{root}/{site_id}',
'deploy_create' => 'on',
'toFTP_enable' => '[unselected]',
'symboliclinks' => array( '.settings' => array( 'action' => 'ignore'),
'_installation' => array( 'action' => 'ignore'),
'administrator' => array( 'action' => 'SL'),
'cache' => array( 'action' => 'mkdir', 'readOnly' => '1'),
'components' => array( 'action' => 'SL'),
'images' => array( 'action' => 'special'),
'includes' => array( 'action' => 'SL'),
'installation' => array( 'action' => 'ignore'),
'language' => array( 'action' => 'SL'),
'libraries' => array( 'action' => 'SL'),
'logs' => array( 'action' => 'mkdir', 'readOnly' => '1'),
'media' => array( 'action' => 'SL'),
'modules' => array( 'action' => 'SL'),
'multisites' => array( 'action' => 'SL'),
'plugins' => array( 'action' => 'SL'),
'templates' => array( 'action' => 'special'),
'tmp' => array( 'action' => 'mkdir', 'readOnly' => '1'),
'xmlrpc' => array( 'action' => 'SL'),
'.buildpath' => array( 'action' => 'ignore'),
'.project' => array( 'action' => 'ignore'),
'htaccess.txt' => array( 'action' => 'SL'),
'robots.txt' => array( 'action' => 'SL'),
'index.php' => array( 'action' => 'redirect', 'readOnly' => '1'),
'index2.php' => array( 'action' => 'redirect', 'readOnly' => '1')),
'dbsharing' => array( ));
$templates['replicMasterSubdomain'] = array(
'fromSiteID' => ':master_db:',
'groupName' => '',
'sku' => '',
'title' => '',
'description' => 'Assume that the Site ID will be subdomain.mydomain.com
and deployed in directory
/home/ACCOUNT/domains/mydomain.com/subdomains/subdomain/public_html',
'validity' => '0',
'validity_unit' => 'days',
'maxsite' => '0',
'expireurl' => '',
'toDomains' => array( 'http://{site_id}', 'http://www.{site_id}'),
'redirect1st' => '',
'ignoreMasterIndex' => '',
'continents' => array( ),
'countries' => array( ),
'regions' => '',
'states' => '',
'cities' => '',
'zipcodes' => '',
'fromLongitude' => '',
'fromLatitude' => '',
'toLongitude' => '',
'toLatitude' => '',
'metro' => '',
'area' => '',
'geoip_ignoreundefined' => '0',
'geoip_ignorepattern' => '',
'geoip_ignoretimeout' => '0',
'sortOrdering' => '',
'browser_types' => array( ),
'browser_langs' => '',
'browser_ignorepattern' => '',
'browser_ignoretimeout' => '0',
'toSiteID' => '',
'shareDB' => '',
'adminUserID' => '0',
'adminUserLogin' => '',
'adminUserName' => '',
'adminUserEmail' => '',
'adminUserPsw' => '',
'toPrefix' => '{site_id}_',
'toSiteName' => '',
'setDefaultJLang' => '',
'setDefaultTemplate' => '',
'setDefaultMenu' => '',
'deploy_dir' => '{home}/domains/{site_id-2}.{site_id-1}/subdomains/{site_id-3}{public}',
'toFTP_enable' => '[unselected]',
'symboliclinks' => array( '.settings' => array( 'action' => 'ignore'),
'_installation' => array( 'action' => 'ignore'),
'administrator' => array( 'action' => 'SL'),
'cache' => array( 'action' => 'mkdir', 'readOnly' => '1'),
'components' => array( 'action' => 'SL'),
'images' => array( 'action' => 'special'),
'includes' => array( 'action' => 'SL'),
'installation' => array( 'action' => 'ignore'),
'language' => array( 'action' => 'SL'),
'libraries' => array( 'action' => 'SL'),
'logs' => array( 'action' => 'mkdir', 'readOnly' => '1'),
'media' => array( 'action' => 'SL'),
'modules' => array( 'action' => 'SL'),
'multisites' => array( 'action' => 'SL'),
'plugins' => array( 'action' => 'SL'),
'templates' => array( 'action' => 'special'),
'tmp' => array( 'action' => 'mkdir', 'readOnly' => '1'),
'xmlrpc' => array( 'action' => 'SL'),
'.buildpath' => array( 'action' => 'ignore'),
'.project' => array( 'action' => 'ignore'),
'htaccess.txt' => array( 'action' => 'SL'),
'robots.txt' => array( 'action' => 'SL'),
'index.php' => array( 'action' => 'redirect', 'readOnly' => '1'),
'index2.php' => array( 'action' => 'redirect', 'readOnly' => '1')),
'dbsharing' => array( ));
$templates['shareMasterDomain'] = array(
'fromSiteID' => ':master_db:',
'groupName' => '',
'sku' => '',
'title' => '',
'description' => 'Assume that the Site ID will be mydomain.com
and deployed in directory
/home/ACCOUNT/domains/mydomain.com/public_html',
'validity' => '0',
'validity_unit' => 'days',
'maxsite' => '0',
'expireurl' => '',
'toDomains' => array( 'http://www.{site_id}', 'http://{site_id}'),
'redirect1st' => '',
'ignoreMasterIndex' => '',
'continents' => array( ),
'countries' => array( ),
'regions' => '',
'states' => '',
'cities' => '',
'zipcodes' => '',
'fromLongitude' => '',
'fromLatitude' => '',
'toLongitude' => '',
'toLatitude' => '',
'metro' => '',
'area' => '',
'geoip_ignoreundefined' => '0',
'geoip_ignorepattern' => '',
'geoip_ignoretimeout' => '0',
'sortOrdering' => '',
'browser_types' => array( ),
'browser_langs' => '',
'browser_ignorepattern' => '',
'browser_ignoretimeout' => '0',
'toSiteID' => '',
'shareDB' => '',
'adminUserID' => '0',
'adminUserLogin' => '',
'adminUserName' => '',
'adminUserEmail' => '',
'adminUserPsw' => '',
'toPrefix' => '{site_id}_',
'toSiteName' => '',
'setDefaultJLang' => '',
'setDefaultTemplate' => '',
'setDefaultMenu' => '',
'deploy_dir' => '{home}/domains/{site_id-2}.{site_id-1}{public}',
'toFTP_enable' => '[unselected]',
'symboliclinks' => array( '.settings' => array( 'action' => 'ignore'),
'_installation' => array( 'action' => 'ignore'),
'administrator' => array( 'action' => 'SL'),
'cache' => array( 'action' => 'mkdir', 'readOnly' => '1'),
'components' => array( 'action' => 'SL'),
'images' => array( 'action' => 'special'),
'includes' => array( 'action' => 'SL'),
'installation' => array( 'action' => 'ignore'),
'language' => array( 'action' => 'SL'),
'libraries' => array( 'action' => 'SL'),
'logs' => array( 'action' => 'mkdir', 'readOnly' => '1'),
'media' => array( 'action' => 'SL'),
'modules' => array( 'action' => 'SL'),
'multisites' => array( 'action' => 'SL'),
'plugins' => array( 'action' => 'SL'),
'templates' => array( 'action' => 'special'),
'tmp' => array( 'action' => 'mkdir', 'readOnly' => '1'),
'xmlrpc' => array( 'action' => 'SL'),
'.buildpath' => array( 'action' => 'ignore'),
'.project' => array( 'action' => 'ignore'),
'htaccess.txt' => array( 'action' => 'SL'),
'robots.txt' => array( 'action' => 'SL'),
'index.php' => array( 'action' => 'redirect', 'readOnly' => '1'),
'index2.php' => array( 'action' => 'redirect', 'readOnly' => '1')),
'dbsharing' => array( 'dbsh_UserSharing' => 'Joomla'));
$templates['shareMasterMultisites'] = array(
'fromSiteID' => ':master_db:',
'groupName' => '',
'sku' => '',
'title' => '',
'description' => '',
'validity' => '0',
'validity_unit' => 'days',
'maxsite' => '0',
'expireurl' => '',
'toDomains' => array( 'http://{site_url}/multisites/{site_id}'),
'redirect1st' => '',
'ignoreMasterIndex' => '',
'continents' => array( ),
'countries' => array( ),
'regions' => '',
'states' => '',
'cities' => '',
'zipcodes' => '',
'fromLongitude' => '',
'fromLatitude' => '',
'toLongitude' => '',
'toLatitude' => '',
'metro' => '',
'area' => '',
'geoip_ignoreundefined' => '0',
'geoip_ignorepattern' => '',
'geoip_ignoretimeout' => '0',
'sortOrdering' => '',
'browser_types' => array( ),
'browser_langs' => '',
'browser_ignorepattern' => '',
'browser_ignoretimeout' => '0',
'toSiteID' => '',
'shareDB' => '',
'adminUserID' => '0',
'adminUserLogin' => '',
'adminUserName' => '',
'adminUserEmail' => '',
'adminUserPsw' => '',
'toPrefix' => '{site_id}_',
'toSiteName' => '',
'setDefaultJLang' => '',
'setDefaultTemplate' => '',
'setDefaultMenu' => '',
'deploy_dir' => '{site_dir}',
'toFTP_enable' => '[unselected]',
'symboliclinks' => array( '.settings' => array( 'action' => 'ignore'),
'_installation' => array( 'action' => 'ignore'),
'administrator' => array( 'action' => 'SL'),
'cache' => array( 'action' => 'mkdir', 'readOnly' => '1'),
'components' => array( 'action' => 'SL'),
'images' => array( 'action' => 'special'),
'includes' => array( 'action' => 'SL'),
'installation' => array( 'action' => 'ignore'),
'language' => array( 'action' => 'SL'),
'libraries' => array( 'action' => 'SL'),
'logs' => array( 'action' => 'mkdir', 'readOnly' => '1'),
'media' => array( 'action' => 'SL'),
'modules' => array( 'action' => 'SL'),
'multisites' => array( 'action' => 'SL'),
'plugins' => array( 'action' => 'SL'),
'templates' => array( 'action' => 'special'),
'tmp' => array( 'action' => 'mkdir', 'readOnly' => '1'),
'xmlrpc' => array( 'action' => 'SL'),
'.buildpath' => array( 'action' => 'ignore'),
'.project' => array( 'action' => 'ignore'),
'htaccess.txt' => array( 'action' => 'SL'),
'robots.txt' => array( 'action' => 'SL'),
'index.php' => array( 'action' => 'redirect', 'readOnly' => '1'),
'index2.php' => array( 'action' => 'redirect', 'readOnly' => '1')),
'dbsharing' => array( 'dbsh_UserSharing' => 'Joomla'));
$templates['shareMasterSubdir'] = array(
'fromSiteID' => ':master_db:',
'groupName' => '',
'sku' => '',
'title' => '',
'description' => '',
'validity' => '0',
'validity_unit' => 'days',
'maxsite' => '0',
'expireurl' => '',
'toDomains' => array( 'http://{site_url}/{site_id}'),
'redirect1st' => '',
'ignoreMasterIndex' => '',
'continents' => array( ),
'countries' => array( ),
'regions' => '',
'states' => '',
'cities' => '',
'zipcodes' => '',
'fromLongitude' => '',
'fromLatitude' => '',
'toLongitude' => '',
'toLatitude' => '',
'metro' => '',
'area' => '',
'geoip_ignoreundefined' => '0',
'geoip_ignorepattern' => '',
'geoip_ignoretimeout' => '0',
'sortOrdering' => '',
'browser_types' => array( ),
'browser_langs' => '',
'browser_ignorepattern' => '',
'browser_ignoretimeout' => '0',
'toSiteID' => '',
'shareDB' => '',
'adminUserID' => '0',
'adminUserLogin' => '',
'adminUserName' => '',
'adminUserEmail' => '',
'adminUserPsw' => '',
'toPrefix' => '{site_id}_',
'toSiteName' => '',
'setDefaultJLang' => '',
'setDefaultTemplate' => '',
'setDefaultMenu' => '',
'deploy_dir' => '{root}/{site_id}',
'deploy_create' => 'on',
'toFTP_enable' => '[unselected]',
'symboliclinks' => array( '.settings' => array( 'action' => 'ignore'),
'_installation' => array( 'action' => 'ignore'),
'administrator' => array( 'action' => 'SL'),
'cache' => array( 'action' => 'mkdir', 'readOnly' => '1'),
'components' => array( 'action' => 'SL'),
'images' => array( 'action' => 'special'),
'includes' => array( 'action' => 'SL'),
'installation' => array( 'action' => 'ignore'),
'language' => array( 'action' => 'SL'),
'libraries' => array( 'action' => 'SL'),
'logs' => array( 'action' => 'mkdir', 'readOnly' => '1'),
'media' => array( 'action' => 'SL'),
'modules' => array( 'action' => 'SL'),
'multisites' => array( 'action' => 'SL'),
'plugins' => array( 'action' => 'SL'),
'templates' => array( 'action' => 'special'),
'tmp' => array( 'action' => 'mkdir', 'readOnly' => '1'),
'xmlrpc' => array( 'action' => 'SL'),
'.buildpath' => array( 'action' => 'ignore'),
'.project' => array( 'action' => 'ignore'),
'htaccess.txt' => array( 'action' => 'SL'),
'robots.txt' => array( 'action' => 'SL'),
'index.php' => array( 'action' => 'redirect', 'readOnly' => '1'),
'index2.php' => array( 'action' => 'redirect', 'readOnly' => '1')),
'dbsharing' => array( 'dbsh_UserSharing' => 'Joomla'));
$templates['shareMasterSubdomain'] = array(
'fromSiteID' => ':master_db:',
'groupName' => '',
'sku' => '',
'title' => '',
'description' => 'Assume that the Site ID will be subdomain.mydomain.com
and deployed in directory
/home/ACCOUNT/domains/mydomain.com/subdomains/subdomain/public_html',
'validity' => '0',
'validity_unit' => 'days',
'maxsite' => '0',
'expireurl' => '',
'toDomains' => array( 'http://{site_id}', 'http://www.{site_id}'),
'redirect1st' => '',
'ignoreMasterIndex' => '',
'continents' => array( ),
'countries' => array( ),
'regions' => '',
'states' => '',
'cities' => '',
'zipcodes' => '',
'fromLongitude' => '',
'fromLatitude' => '',
'toLongitude' => '',
'toLatitude' => '',
'metro' => '',
'area' => '',
'geoip_ignoreundefined' => '0',
'geoip_ignorepattern' => '',
'geoip_ignoretimeout' => '0',
'sortOrdering' => '',
'browser_types' => array( ),
'browser_langs' => '',
'browser_ignorepattern' => '',
'browser_ignoretimeout' => '0',
'toSiteID' => '',
'shareDB' => '',
'adminUserID' => '0',
'adminUserLogin' => '',
'adminUserName' => '',
'adminUserEmail' => '',
'adminUserPsw' => '',
'toPrefix' => '{site_id}_',
'toSiteName' => '',
'setDefaultJLang' => '',
'setDefaultTemplate' => '',
'setDefaultMenu' => '',
'deploy_dir' => '{home}/domains/{site_id-2}.{site_id-1}/subdomains/{site_id-3}{public}',
'toFTP_enable' => '[unselected]',
'symboliclinks' => array( '.settings' => array( 'action' => 'ignore'),
'_installation' => array( 'action' => 'ignore'),
'administrator' => array( 'action' => 'SL'),
'cache' => array( 'action' => 'mkdir', 'readOnly' => '1'),
'components' => array( 'action' => 'SL'),
'images' => array( 'action' => 'special'),
'includes' => array( 'action' => 'SL'),
'installation' => array( 'action' => 'ignore'),
'language' => array( 'action' => 'SL'),
'libraries' => array( 'action' => 'SL'),
'logs' => array( 'action' => 'mkdir', 'readOnly' => '1'),
'media' => array( 'action' => 'SL'),
'modules' => array( 'action' => 'SL'),
'multisites' => array( 'action' => 'SL'),
'plugins' => array( 'action' => 'SL'),
'templates' => array( 'action' => 'special'),
'tmp' => array( 'action' => 'mkdir', 'readOnly' => '1'),
'xmlrpc' => array( 'action' => 'SL'),
'.buildpath' => array( 'action' => 'ignore'),
'.project' => array( 'action' => 'ignore'),
'htaccess.txt' => array( 'action' => 'SL'),
'robots.txt' => array( 'action' => 'SL'),
'index.php' => array( 'action' => 'redirect', 'readOnly' => '1'),
'index2.php' => array( 'action' => 'redirect', 'readOnly' => '1')),
'dbsharing' => array( 'dbsh_UserSharing' => 'Joomla'));
